version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "cd nextjs-dashboard && pnpm dev"